freeserf/freeserf

src/data-source-dos.cc
src/serf.c
src/viewport.cc

#183 Crash in viewport_t::draw_active_serf on higher game speed

Fixed: #183 Crash in viewport_t::draw_active_serf on higher game speed

---

README.md
src/event_loop-sdl.cc
src/event_loop-sdl.h
src/gfx.cc
src/gfx.h
src/video-sdl.cc
src/video-sdl.h
src/video.h

Simple zooming with CTRL+mause wheel and keyboard '[' ']'

Zoom with CTRL+mause wheel and keyboard '[' ']'

---

.gitignore
Makefile.am
src/game-init.cc
src/game-init.h
src/interface.cc
src/minimap.cc
src/minimap.h
src/mission.cc
src/popup.cc
src/popup.h
src/text-input.cc
src/text-input.h
windows/freeserf.vcproj

Added: random base input for custom game
Added: map preview for all games

Game init window improvements

---

HACKING.md
appveyor.yml
windows/freeserf.vcproj

Added SDL2 DLLs coping to Visual Studio project
Added more instructions for Windows build

Fixed: Windows build instructions #61

---

src/building.cc
src/building.h
src/event_loop-sdl.cc
src/flag.cc
src/flag.h
src/game.cc
src/inventory.cc
src/inventory.h
src/map.cc
src/map.h
src/player.cc
src/player.h
src/popup.cc
src/savegame.cc
src/serf.cc
src/serf.h
src/video-sdl.h
src/viewport.cc
src/xmi2mid.cc

Fixed #192 and all gcc warnings

Fix #192 Too many building materials requested / sent

---

appveyor.yml
src/freeserf.cc
src/mission.cc
src/mission.h

Fix #102: All missions are available now

---

src/data.cc

* add freeserf execution directory to add_to_search_paths for windows
* add "path" environment variable for Windows in replacement of "XDG_DATA_DIRS" for POSIX OS

data search paths for windows

---

src/game.cc
src/map.cc
src/map.h

* fix bug in [game.cc -> bool game_t::load_mission_map(int level) ] causes wrong mission-random is used
* fix error in is_valid_extension() if the road has zero length (may only occurs in MS Studio)
* fix add_gold_deposit() with negative delta

separated bug fixes

---

configure.ac

Changed: version -> 0.2

---

src/game-init.cc

Custom game map and preview the same now

Fix #212: Incorrect minimap preview in game init box

---

src/event_loop-sdl.cc
src/event_loop.h
src/panel.cc
src/panel.h

Notification icon blinking are restored.
Added timer_t class.

Fix #211: Animation of message icon in panel is not running

---

src/map.cc
src/map.h
src/viewport.cc
src/viewport.h

Fix #144: Auto change cursor after building burn/flag removal

---

appveyor.yml

appveyor: Cache SDL2 and SDL2_mixer downloads

---

src/flag.cc
src/game.cc
src/map-generator.cc
src/map.cc
src/map.h
src/pathfinder.cc
src/serf.cc
src/viewport.cc

Add inline function that replaces the `DIR_REVERSE` macro. Also add `turn_direction()` for turning any number of steps. This is used to simplify the code in a few places in the map generator.

map: Add reverse_direction() and turn_direction()

---

src/building.cc
src/flag.cc
src/game.cc
src/map.h
src/player.cc
src/serf.cc
src/serf.h
src/viewport.cc

Fixed #224
Fixed some potential errors with comparing bool.

Fix #224 Sending geologist to flag gives wrong GUI feedback

---

src/building.cc
src/data-source-dos.cc
src/game.cc
src/game.h
src/interface.cc
src/player.cc
src/player.h
src/popup.cc
src/popup.h
src/serf.cc

Cause my other Pull Request may never will be used, here are only the fixes that I have done there:
+ bugfix: crash in Interface::build_road_segment()
+ bugfix: in data-source-dos: get_object()
+ Add Enum PopupBox::BackgroundPattern
+ Update use of Enum Message::Type

Fixes from my "missions and tutorial conditions" pull

---

src/building.cc
src/building.h
src/flag.cc
src/flag.h
src/game.cc
src/game.h
src/map.cc
src/map.h
src/objects.h
src/player.h

First two commits changes methods in `objects.h` to const, adds a const `operator[]` and a const iterator. Remaining commits change getter methods in `Map`, `Building`, `Flag`, `Player` and `Game` to const.

Make more methods const

---

src/game.cc
src/map-geometry.h
src/map.h
src/pathfinder.cc
src/player.cc
src/serf.cc
src/viewport.cc

Add method `pos_add()` that takes individual x, y values and add `dist_x()` and `dist_y()` to calculate distance between positions.

Map geometry functions

---

src/minimap.cc
src/minimap.h
src/popup.cc
src/viewport.cc

Bit flags replaced with boolean members for better readability.

Refactoring: minimap modes

---

src/freeserf.cc
src/game-init.cc
src/game-init.h
src/game.cc
src/game.h
src/map-geometry.h
src/mission.cc
src/mission.h
src/player.cc
src/player.h
tests/test_save_game.cc

Added: PlayerInfo, GameInfo
Those classes may be used for publishing (via network) info about game.

Refactoring: extend Mission to class enough for game initiation

---

src/map.cc

Fix #297: Incorrect map ownership on some maps

---

src/audio-sdlmixer.cc
src/data-source-amiga.cc
src/data-source-amiga.h
src/data-source-dos.cc
src/data-source-dos.h
src/data-source.cc
src/data-source.h
src/data.cc
src/data.h
src/freeserf.cc
src/gfx.cc
src/gfx.h
src/viewport.h

Refactoring: DataSource and it's realizations
Fix #320: Colors of flags

Fix #320: Colors of flags

---

src/buffer.cc
src/buffer.h
src/data-source-amiga.cc

Fixed: amiga map object shadows
Fixed: crash while memory buffer grows

Fixes: crash while memory buffer grows, amiga map object shadows

---

src/map.cc
src/map.h
src/pathfinder.cc
src/pathfinder.h
src/viewport.cc

Check intersection while path find

Fix #363: Road construction

---

src/game.cc
src/list.cc
src/savegame.cc

Fixed: legacy save file loading

---

CMakeLists.txt
src/CMakeLists.txt
src/flag.cc
src/freeserf.cc
src/profiler.cc
src/profiler.h
src/serf.cc

tool for profiling only game engine, without the influence of graphics, audio, etc.

Add profiling tool

---

src/audio-sdlmixer.cc
src/audio.h
src/video-sdl.cc

mainely for logging SDL libs versions

Improve logging

---

CMakeLists.txt
cmake/CppLint.cmake
src/CMakeLists.txt
tests/CMakeLists.txt

- style check and test targets gather to folders in IDE

Project organization improved

---

CMakeLists.txt

Changed: version -> 0.3

---

src/sprite-file-sdl.cc
src/sprite-file.h

- fixed build without SDL2_image

Fix #412: build fails on sprite-file-dummy and data-source-custom

---

src/game-init.cc
src/interface.cc

Fix #411: options button on main loading screen not clickable

---

src/audio-sdlmixer.cc
src/audio-sdlmixer.h

Fix #417: music doesn't loop forever

---

src/audio-sdlmixer.cc
src/building.cc
src/data-source-amiga.cc
src/debug.cc
src/debug.h
src/flag.cc
src/freeserf.cc
src/game-init.cc
src/game.cc
src/gui.cc
src/interface.cc
src/inventory.cc
src/log.h
src/map-geometry.h
src/mission.cc
src/objects.h
src/pathfinder.cc
src/player.cc
src/popup.cc
src/popup.h
src/video-sdl.h

- fixed VS warnings
- fixed static analyzer warnings

Fixed: some warnings
