- src/inventory.cc
There was a bug in the function **inventory_t::push_resource** where the operations of the ternary operator were inverted. This meant that when a resource was delivered to the castle, the stock of that resource was not incremented. This pull request should fix that.
> Fix inventory bug

- src/serf.cc
Previously all notifications from geologists would say that gold was found. This was fixed to report the correct resource type.
> Fix incorrect geologist notification

- src/map.h
Add comments documenting directions on the map (`dir_t`) and the `DIR_REVERSE()` macro.
> Fix #169: Add comment documenting dir_t and DIR_REVERSE()

- src/game-init.cc
- src/game-init.h
"backgraund" -> "background", "priview" -> "preview"
> game-init: Fix some typos in method names

- appveyor.yml
I noticed that AppVeyor often fails to build because of a failure to download the SDL zip files. AppVeyor suggests (http://www.appveyor.com/docs/how-to/http-proxy) enabling HTTP proxy to alleviate this.
@wdigger Maybe try this for the PR #216 that keeps failing.
> appveyor: Enable HTTP proxy

- src/map.cc
Explain how the map tile elevation (height) is encoded as well as the terrain type and the relation between elevation, terrain and adjacency to other terrains.
> map: Add comment on elevation and terrain types

- appveyor.yml
Previously the `INCLUDE` and `LIB` environment variables were not set when the cached directory was found. This is now fixed.
> appveyor: Fix SDL env variables when using AppVeyor cache

- src/game.cc
- src/game.h
- src/map.cc
- src/map.h
- src/player.cc
- src/serf.cc
- src/viewport.cc
Add `map_terrain_t` enum for `type_up` and `type_down` map tile fields based on the documentation in the last PR.
Second commit renames a map generator method and changes how the map terrain type range is provided.
> Add map terrain enum

- src/serf.cc
Fixes bug in `serf::set_type()` where the type `SERF_TRANSPORTER_INVENTORY` should be counted in the player counter of total serfs as a `SERF_TRANSPORTER`. The bug caused an incorrect update when a serf of the former type was changed to a different type which caused the total `SERF_TRANSPORTER` count to be incorrect.
> serf: Fix bug where serf counters are changed incorrectly

- src/game.cc
Revert to the behaviour before 56c30113 when the `game::random_int()` was changed to use the map randomness source to generate random numbers. The game randomness is saved in the save game which guarantees the same game progression after a save game is loaded.
> game: Revert to using the random_state_t from save game

- src/interface.cc
- src/map.cc
- src/map.h
- src/pathfinder.cc
`extand` -> `extend`, `is_extandable` -> `is_extendable`
> map: Fix typos in Road method names

- src/game-init.cc
- src/game.cc
- src/map-generator.cc
- src/map-generator.h
- src/map.cc
- src/map.h
First commit changes `get_rnd_coord()` on `Map` to const. Since this method no longer uses a `Random` on `Map` it can safely be made const. This is necessary for the second commit.
Second commit changes the `ClassicMapGenerator` to hold a const reference to `Map` instead of a (non-const) pointer. A const reference is preferable since the `Map` should not be changed through the map generator. This results in a lot of changes in `map-generator.cc` but these are simply a search-replace of `map->` to `map.`.
> Map const reference

- src/game.cc
Fixes regression from 96e1104 which made it impossible to build mines on the border between tundra and grass.
> game: Fix bug that made mines impossible to build in some places

- src/inventory.cc
- src/inventory.h
- src/player.cc
- src/serf.cc
"sers_away" -> "serf_away", "serf_potencial_count" -> "serf_potential_count"
> inventory: Fix typos in method names

- src/serf.cc
Fix regression introduced in d23e43a which changed the delta variable in `Serf::train_knight()` from uint16_t to int. This change meant that when the game tick counter (an unsigned int) became larger than 0x10000 the delta in `train_knight()` would always be >= 0x10000. This resulted in the training loop running more than 10 times for every update step for every knight.
> Fix regression causing all knights to be instantly promoted

- .travis.yml
- tests/test_map.cc
Fixes a suggestion about adding a copyright header to `test_map.cc`, then includes `test_map.cc` in the files checked by cpplint on Travis CI.
> Run cpplint on test program source

- src/map.h
Fix regression introduced in 5862cb3 where owner == 0 was changed to mean that the land has no owner. This resulted in the first player (player 0) not being able to own any land. Fixed by incrementing the stored player number by one such that 0 indicates no owner, player 0 is indicated by 1, and so on.
> Fix regression causing incorrect land owner

- Makefile.am
- src/freeserf.cc
- src/game.cc
- src/savegame.cc
- src/savegame.h
- tests/test_save_game.cc
First two commits change the load/save state functions in `savegame.cc` to use the iostream API instead of using `FILE`. This makes it easier to implement a test program using `stringstream` from the iostream API.
Next commit fixes a bug that initially made this test fail. This is a regression from a while back that only affected save games where no buildings were present.
Lastly, the test program is added which starts a game, saves the game state, then tries to load it back. It doesn't yet check whether the loaded state is correct. I would expand this test in the future since it seems that there are still a number of bugs when loading a game file.
> Add test program for saving and loading game

- src/game.cc
- src/map.cc
- src/map.h
- tests/test_save_game.cc
First two commits organize the map update state into a separate struct. Third commit is adding map update state and gold deposit to loaded and saved state for game. Fourth commit resets gold deposit when initializing Map. This is needed to load the gold deposit value correctly. Fifth commit fixes a bug where the map ownership is loaded incorrectly. Sixth commit adds an `operator ==` on Map to allow comparing two Map instances. Last commit checks the map equality of the original and the loaded game in `test_save_game`.
In the future I think the `gold_deposit` state should probably be moved to Game. It can also possibly be recalculated after loading the game instead of storing it in the save game file. The map tile ownership could also probably be removed from the save game and recalculated …
> Test loaded map

- src/freeserf.cc
- src/game-init.cc
- src/game.cc
- src/game.h
- src/savegame.cc
- tests/test_save_game.cc
Removes map generator parameter from command line and from `Game` constructor. The `map_generator` member in `Game` was no longer used.
> game: Remove map generator constructor parameter

- src/game.cc
- src/game.h
- src/map.cc
- src/map.h
- src/player.cc
- tests/test_save_game.cc
Previously the `Map` was keeping track of the total amount of gold in the game (including unmined gold ore, gold at flags/inventories/other buildings, transported gold/ore, etc.) This counter was moved to Game and a method on `Map` was added to return the current amount of gold in mineral deposits. The name of the method on `Game` was changed from `get_gold_deposit()` to `get_gold_total()` since the method is really counting the total gold present in the game, not just the gold deposited as minerals in the map.
> Move total gold counter to Game

- src/map.cc
Land ownership is already restored after loading a game with `init_land_ownership()` in `Game`. The ownership information in the save game is redundant.
> map: Remove load/save of owner field

- src/game.cc
- src/savegame.cc
- src/savegame.h
`SaveReaderBinary` is changed so that `has_data_left()` is checked before every read to guard against reads outside of the underlying memory area. An exception is thrown when this happens.  Second commit fixed `load_v0_state()` which would always return true and not allow the loaded `Game` state to be accessed. Third commit logs load game failures to make debugging easier. Last commit adds an additional check for map size so that the load fails when the map size is too small or too large.
> Fail properly when trying to load binary save games instead of segfaulting

- src/game.cc
- src/game.h
- src/popup.cc
Removes `gat_flag_at_pos()` which is a redundant copy of the method `get_flag_at_pos()`.
> game: Remove redundant method with misspelled name

- src/game.cc
- tests/test_save_game.cc
Add checks that verify that land ownership and player object is restored after saving and loading a game. Fixes a bug where the land ownership value for players were not initialized to zero when loading a game which resulted in a random land ownership value after loading.
> Test player restore

- src/flag.cc
Simplify a counter-clockwise loop over directions by looping directly CCW instead of looping clockwise and then converting the `Direction`.
> flag: Simplify direction loop

- Makefile.am
- src/game-init.cc
- src/game.cc
- src/map-generator.cc
- src/map-geometry.h
- src/map.cc
- src/map.h
- src/minimap.cc
- tests/test_map.cc
First commit separates the map landscape/game tiles from the position/dimension/movement. The latter part is moved into the `MapGeometry` class. This should make it easier to test this part separately. The `Map` is changed to be constructed from a `MapGeometry` so more initialization of the `Map` is moved to the constructor.
Second commit adds an iterator over all `MapPos` in the map. This simplifies a number of loops that iterate linearly over the map. 
Third commit further cleans up construction and destruction of `Map` by using `unique_ptr` for memory management.
> Map geometry

- src/game.cc
- src/player.cc
- src/player.h
The `init()` method on `Player` takes an argument which overwrites the game object number (`index`) on the parent class. This is unnecessary because the game object number is already assigned by the constructor and should not be changed. This bug became apparent after 06a0e3b was applied. When certain save games were loaded the game would freeze on quit.
> player: Fix init() taking unnecessary game object number

- src/map.cc
This fixes an apparent bug in `set_object()` where the six directions are iterated to get the six positions surrounding the original position but `on_object_changed()` is called with the original positions resulting in six identical calls. I'm not entirely sure why this even has to call `on_object_changed()` on more than one position but for now this fix at least changes it to do something meaningful.
> map: Fix bug in call to on_object_changed()

- src/game.cc
- src/game.h
- src/objects.h
First commit changes `Collection` to handle game objects with smart pointers. Second commit removes the calls to `erase()` in `Game::deinit()` since the smart pointers automatically free the game objects when the `Game` is destroyed. Third commit changes the `Map` instance in `Game` to also be handled with smart pointer.
Fourth and fifth commit change `GameObject` to be stored directly in the objects map of the `Collection`, avoiding the indirection through the smart pointer.
> Handle game objects in Collection with smart pointer

- Makefile.am
- src/flag.cc
- src/game.cc
- src/interface.cc
- src/map-generator.cc
- src/map-geometry.h
- src/map.cc
- src/pathfinder.cc
- src/popup.cc
- src/serf.cc
- src/viewport.cc
- tests/test_map_geometry.cc
Adds iterator to cycle through directions. Simplifies many loops because the syntax is easier and safer than manually looping through the `Direction` enum and the iterator provides correctly typed values that don't need to be cast manually to `Direction`.
> Direction iterator

- src/flag.cc
- src/map-generator.cc
- src/map-geometry.h
- src/map.h
- src/minimap.cc
Remove `DirectionUpRight` and `DirectionDownLeft` from the `Direction` enum. These two directions are the non-standard directions because they do not correspond to a tile edge on the map that can be traversed. These directions were only used in a few places for movement and were easily converted to two standard direction movements.
> map-geometry: Remove non-standard directions

- src/data.cc
- src/data.h
- src/freeserf.cc
- Make sure that the singleton instance of `Data` is never copied and that it is always destroyed.
- Handle memory with smart pointer.
- Move the functionality that gathers standard search paths to separate method. Fixes a bug where the root directory (`/`) would be searched for data files.
- Restore functionality where standard paths are only searched if a nullptr/empty string is given.
- Add documentation and update usage help message shown when running `freeserf -h`.
> Various data.cc cleanup

- src/audio-dummy.h
The return types of `get_sound_player()` and `get_music_player()` seem to have been changed to `PPlayer` without updating `audio-dummy.h`.
> Fix build with audio-dummy

- Makefile.am
- src/version-vcs.h.in
- src/version.cc
Generates `version-vcs.h` from template file instead of embedding the contents in the `Makefile.am` rule.
> Makefile.am: Generate version-vcs.h from template file

- src/audio-sdlmixer.cc
- src/audio-sdlmixer.h
- src/audio.h
- src/gfx.cc
- src/gfx.h
- src/savegame.cc
- src/savegame.h
- src/video-sdl.cc
- src/video-sdl.h
- src/video.cc
- src/video.h
Guys, this is deprecated for 6 years. Why are you still using this?
> Getting rid of 'dynamic exception specifications are deprecated in C++11' warnings

- src/flag.cc
- src/flag.h
- src/game.cc
- src/gfx.cc
- src/serf.cc
- src/serf.h
Fixed: legacy transporter state loading
Fixed: crash on drawing if wrong sprite index occurs
> Fix #375: Save game functionality does not work in v0.2 and last build version

- src/viewport.cc
> Fix #415: double-clicking on a burning building causes game to crash

- src/random.h
error:
```
In file included from /usr/src/freeserf-git/src/freeserf/src/random.cc:22:
/usr/src/freeserf-git/src/freeserf/src/random.h:29:3: error: ‘uint16_t’ does not name a type
29 |   uint16_t state[3];
|   ^~~~~~~~
/usr/src/freeserf-git/src/freeserf/src/random.h:26:1: note: ‘uint16_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
25 | #include <string>
+++ |+#include <cstdint>
26 | 
```
> Fix compilation: update random.h
